modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="humbleadditions"
version="${file.jarVersion}"
displayName="Humble Additions"
logoFile="pack.png"
#credits=""
authors="Christofmeg"
description='''
Adds small features and additions for the humble player.
'''
[[dependencies.humbleadditions]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.humbleadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
